# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_rpc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 531)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 12, 651, 501))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_char_icon = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_char_icon.setGeometry(QtCore.QRect(156, 39, 291, 22))
        self.comboBox_char_icon.setObjectName("comboBox_char_icon")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(22, 41, 151, 16))
        self.label.setObjectName("label")
        self.lineEdit_char_icon = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_char_icon.setGeometry(QtCore.QRect(466, 39, 151, 21))
        self.lineEdit_char_icon.setObjectName("lineEdit_char_icon")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 93, 591, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_text_1 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_text_1.setGeometry(QtCore.QRect(20, 119, 601, 87))
        self.textEdit_text_1.setObjectName("textEdit_text_1")
        self.textEdit_text_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_text_2.setGeometry(QtCore.QRect(20, 259, 601, 87))
        self.textEdit_text_2.setObjectName("textEdit_text_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 233, 601, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox_show_timestamp = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_show_timestamp.setGeometry(QtCore.QRect(32, 375, 171, 21))
        self.checkBox_show_timestamp.setObjectName("checkBox_show_timestamp")
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_connect.setGeometry(QtCore.QRect(360, 420, 201, 61))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_save_changes = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save_changes.setGeometry(QtCore.QRect(69, 420, 201, 61))
        self.pushButton_save_changes.setObjectName("pushButton_save_changes")
        self.checkBox_auto_conn = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_auto_conn.setGeometry(QtCore.QRect(231, 375, 401, 21))
        self.checkBox_auto_conn.setObjectName("checkBox_auto_conn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "umamusume RPC"))
        self.groupBox.setTitle(_translate("MainWindow", "Discord Rich Presence Config"))
        self.label.setText(_translate("MainWindow", "character icon"))
        self.label_2.setText(_translate("MainWindow", "What are you doing? (Greater than 2 and less than 128 characters)"))
        self.label_3.setText(_translate("MainWindow", "How are you feeling now? (Greater than 2 and less than 128 characters)"))
        self.checkBox_show_timestamp.setText(_translate("MainWindow", "show timestamp"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect To Discord"))
        self.pushButton_save_changes.setText(_translate("MainWindow", "Save Changes"))
        self.checkBox_auto_conn.setText(_translate("MainWindow", "automatically connect to Discord on startup"))
